{% set name = "sphinxext-altair" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinxext_altair-{{ version }}.tar.gz
  sha256: eac920f97fdc9d44b669f442c24f6d96ea4f236179b96c25df41a8cd4385e5f6

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - altair >=4.0.0
    - docutils
    - jinja2
    - sphinx
    - typing_extensions >=4.0.1

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - sphinxext_altair.altairplot

about:
  home: http://altair-viz.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: sphinxext-altair provides the directive altair-plot to insert live-rendered Altair plots within your Sphinx documentation.

extra:
  recipe-maintainers:
    - binste
    - jtilly
    - mattijn
