{% set name = "sphinxext-altair" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinxext_altair-{{ version }}.tar.gz
  sha256: b531b269b2012944dc9a89faa1204e6df8279560da98b2d219ea64caf3d62ec5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - altair >=4.0
    - docutils
    - sphinx
    - typing_extensions >=4.0.1

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - sphinxext_altair.altairplot

about:
  home: http://altair-viz.github.io
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'sphinxext-altair provides the directive altair-plot to insert live-rendered Altair plots within your Sphinx documentation.'

extra:
  recipe-maintainers:
    - binste
    - jtilly
    - mattijn
